### ISSUE TITLE
UI selects valid GPIO value for unchecked GPIO options

### ISSUE THREAD

**Issue by NDJ-EZLO** [ezloteam/Ezlo_Pi#24]
While configuring "Other" device type we set multiple GPIOs through check-boxes and select required GPIO number. However, if the GPIO checkbox is not set and set-config is clicked, the UI sets un-checked options to valid GPIO number randomly and configures the device accordingly.

**Comment by lomasSE89** [comment]
fixed at [commit](https://github.com/ezloteam/Ezlo_Pi/commit/d2d4d0dc1f5a59582e30744adc26684418ade58d)
